name: replay_classification
channels:
- conda-forge
- defaults
- ioam
dependencies:
- "python>=3.5"
- setuptools
- numpy
- scipy
- pandas
- xarray
- statsmodels
- matplotlib
- seaborn
- patsy
- pytest
- jupyter
- coveralls
- pytest-cov
- numba
- holoviews
- bokeh
